version: '3'

services:
  nginx:
<<<<<<< HEAD
    image: jwilder/nginx-proxy
    container_name: nginx
    environment:
      - DEFAULT_HOST=ugosty.ru
      - VIRTUAL_HOST=ugosty.ru
      - VIRTUAL_PORT=80
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always
=======
   

    image: nginx:latest
    volumes:
    
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./react/dist:/usr/share/nginx/html


    

    ports:
     - "80:80"
     - "443:443"

    depends_on:
        - app




    

  
>>>>>>> df2844d (ssl)
