version: '3'

services:
  app:
    build: ./react
    ports:
      - "3000:80"
    volumes:
      - ./react/dist:/app/dist
    container_name: reactapp
    

  nginx:
   

    image: nginx:latest
    volumes:
    
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./react/dist:/usr/share/nginx/html

    - ./nginx/certbot/conf:/etc/letsencrypt
    - ./nginx/certbot/www:/var/www/certbot

    

    ports:
     - "80:80"
     - "443:443"

    depends_on:
        - app



  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; certbot renew; sleep 12h & wait'"
    

  